# Generated by Django 5.2.8 on 2025-12-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256)),
                ('referenceId', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
    ]
