# Generated by Django 5.2.8 on 2025-12-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_payment_amount_payment_fecamds_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='time_of_payment',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
