# Generated by Django 5.2.8 on 2025-12-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_payment_time_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fecamds_class',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='set_year',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
