# Generated by Django 5.2.8 on 2025-12-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_payment_fecamds_class_alter_payment_set_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='fecamds_class',
            field=models.CharField(blank=True, choices=[('St Joan class', 'St Joan class'), ('St Anselem class', 'St Anselem class'), ('St Francis class', 'St Francis class'), ('St Mary class', 'St Mary class'), ('St Raphael class', 'St Raphael class'), ('St Bendict class', 'St Bendict class'), ('St Lucy class', 'St Lucy class'), ('St Micheal class', 'St Micheal class')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='set_year',
            field=models.CharField(blank=True, choices=[('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecamds_class',
            field=models.CharField(blank=True, choices=[('St Joan class', 'St Joan class'), ('St Anselem class', 'St Anselem class'), ('St Francis class', 'St Francis class'), ('St Mary class', 'St Mary class'), ('St Raphael class', 'St Raphael class'), ('St Bendict class', 'St Bendict class'), ('St Lucy class', 'St Lucy class'), ('St Micheal class', 'St Micheal class')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='set_year',
            field=models.CharField(blank=True, choices=[('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=256, null=True),
        ),
    ]
